//Author Name: David Munoz
//Date: 3/15/2020
//Program Name: Munoz_Text_Analyzer
//Purpose: Analyze the words in given text file

package MunozTextAnalyzer;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * @author King David
 */
public class Munoz_Text_Analyzer extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Munoz_Text_Analyzer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Analyzer");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Press start to analyze the words in Macbeth.");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("txtResult");

        jButton2.setLabel("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("btnStart");
        jScrollPane1.getAccessibleContext().setAccessibleName("txtResults");
        jButton2.getAccessibleContext().setAccessibleName("btnExit");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Method run when exit button is pressed
     * 
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Method run when start button is pressed
     * Calls all methods necessary to complete processing of text analyzer app
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            File file = new File("macbeth.txt");
            Map<String, Integer> wordMap = runAnalyzer(file);
            Map<String, Integer> result = createFinalWordList(wordMap);
            writeToTextArea(result);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Munoz_Text_Analyzer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Main method creates and displays form
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Munoz_Text_Analyzer().setVisible(true);
            }
        });
    }
    
    /**
     * This method performs processing on file and places formatted words and counts into Map to be returned
     * 
     * @param file we are processing
     * @return
     * @throws FileNotFoundException 
     */
    public static Map runAnalyzer(File file) throws FileNotFoundException{
        
        Scanner sc = new Scanner(file); //scan given file name
        
        ArrayList<String> stringArrayList = new ArrayList(); // ArrayList to hold each word in the file
        String currentWord = ""; // current word being scanned
        String nonWord = ""; // to hold non words
        String[] delimitedWord = new String[2]; // string array to separate words with punctuation attached
        
        Map<String, Integer> wordMap = new HashMap(); // map to hold word and count combination
        
        while(sc.hasNext()){
            currentWord = sc.next();
            if (currentWord.endsWith("!")||currentWord.endsWith(".")||currentWord.endsWith("?")||currentWord.endsWith(";")||currentWord.endsWith(",")||currentWord.endsWith(":")||currentWord.endsWith("-")){ // if there is punctuation attached to word
                delimitedWord = currentWord.split("[!.?;:,-]"); // split the word from punctuation
                currentWord = delimitedWord[0]; //place word without punctuation into currentWord variable
            }
            //if (currentWord.endsWith("|")) //this if statement prevents | from being placed into the list
                //currentWord = nonWord;
            stringArrayList.add(currentWord.toLowerCase()); // add formatted word to arraylist
        } 
        
        for(int i = 0; i < stringArrayList.size();i++){ // for loop iterates through each item in stringArrayList
            String testWord = stringArrayList.get(i); // word at index i is placed into string variable testWord
            
            if(!(wordMap.containsKey(testWord))){ // if wordMap does not contain testWord
                int incrementer = 0; // set incrementer to 0
                    
                for(int j = 0; j < stringArrayList.size();j++){ // second for loop iterates through stringArrayList
                    if(testWord.equalsIgnoreCase(stringArrayList.get(j))){ // if testWord is equivalent to word at index j in stringArrayList
                    incrementer++; // increment the incrementer
                    } 
                }
                wordMap.put(testWord, incrementer); // place current word and count of word usage into wordMap
            }  
        }
        return wordMap;
    }
    /**
     * This method performs final processing on wordMap
     * opens stream on wordMap and sorts keys by values, places these entries into reverse order, takes top 20 results and returns variable result
     * which is  LinkedHashMap<String, Integer> that keeps the order of the entries in it
     * 
     * @param wordMap formatted words placed into this Map along with count of each word
     * @return 
     */
    public static LinkedHashMap createFinalWordList(Map<String, Integer> wordMap){
        
        LinkedHashMap<String, Integer> result = new LinkedHashMap(); // new LinkedHashMap to keep order of items
        
        wordMap.entrySet() // access each entry in map
                .stream() // open stream
                .sorted(Map.Entry.comparingByValue(Comparator.reverseOrder())) //sort by value and reverse order
                .limit(20) // limit 20 entries
                .forEachOrdered(x -> result.put(x.getKey(), x.getValue())); // put each key and value pair into result LinkedHashMap
        
        return result;
    }
   
    /**
     * This method accesses each entry in wordMap and appends it to the jTextArea on the form to be displayed to the user
     * 
     * @param result finalized and formatted wordMap
     */
    private void writeToTextArea(Map<String,Integer> result){
        for(Map.Entry<String, Integer> entry : result.entrySet()){
            jTextArea1.append(entry.toString() + '\n');
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
